# room_sensor_core.cmake — defines portable core sources and includes

set(CORE_SRC
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/App/Src/app.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/App/Src/room_state.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/App/Src/config.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/App/Src/self_test.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/App/Src/device_identity.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Drivers/veml7700/Src/veml7700.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Drivers/display/Src/display.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Storage/Src/storage.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Telemetry/Src/telemetry.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Telemetry/Src/telemetry_serializer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Communication/Src/communication.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Communication/Src/communication_debug.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Command/Src/command.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Command/Src/command_parser.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Command/Src/command_dispatcher.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Command/Src/command_response.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Device/Src/device_manifest.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Device/Src/device_capabilities.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Device/Src/firmware_metadata.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Device/Src/boot_session.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Device/Src/device_manifest_serializer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Device/Src/device_lifecycle.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Provisioning/Src/provisioning.c
)

set(CORE_INC
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/App/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Drivers/veml7700/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Drivers/display/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Platform/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Storage/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Telemetry/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Communication/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Command/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Device/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Provisioning/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Common/Inc
)